### ISSUE TITLE
Q: Is this production ready

### ISSUE THREAD

**Issue by RobertDober** [pragdave/private#1]
Dave, as you might know ;), in Earmark we have quite some functions which are public for the sole reason to be tested (`@doc false` kludge).
I'd love to use `private` instead, ok?

**Comment by pragdave** [comment]
You can be my first user... I promise to support you, but you might want to
try it in a branch..

**Comment by RobertDober** [comment]
going for it, just realized:
we took care not to have any production env dependency for the ex_doc dependency loop, but I will test it anywyay

Well it works fine but I am not testing the application anymore, because the private functions are public in **all** tests, right.

Would we not need something like a tag based approach in which in each test I can make only a given subset of private functions public? (ideally one)

**Comment by pragdave** [comment]
Mon brave

**Comment by RobertDober** [comment]
If even possible ( I guess not) it would be a mess, but what about a unit_test Mix environment?

**Comment by pragdave** [comment]
Explain, svp

**Comment by RobertDober** [comment]
I'll make an example app after work today.

**Comment by RobertDober** [comment]
https://github.com/RobertDober/private_usecase/blob/master/lib/user.ex
this is the _client_ code that calls *incorrectly* into the module using private, yet the code compiles and the tests do not catch the runtime error.

Now I realize that the compiler catches the _normal cases_, but as you do not have control over client code I am kinda worried.

It was this case that made me think about using a dedicated `unit_test` Mix environment in which private functions become public only. If I understand correctly the changes in the code would be trivial, however I yet have to figure out how `ExUnit` can change the env for unit tests easily.

**Comment by pragdave** [comment]
this would also be caught if the tests were run in :dev mode.

I'm not sure it's a common enough issue to lose the benefits of testability.

However, if it is an issue, I could always create a log of calls to what
should be private methods during testing, and filter out those coming
directly from a test. If any remained, I could generate a failure.

Would that help?

**Comment by RobertDober** [comment]
The dev env idea works, however the tests have to be run as follows
```
     mix test test/unit
     MIX_ENV=dev mix test test/acceptance # or any other env != :test
```
A tag based approach would run into compiler issues inside the acceptance tests.

For the second approach I am not sure to understand correctly, what happens if a
private function `a` calls private function `b` of the same module correctly. Well I guess the filter mechanism could figure that out. Hmm that might be of great value, and much work too :cry:

Anyway I like tesing privat functions, José really does not agree, but I believe radical views are rarely correct and **some** private functions benefit from testing.

**Comment by pragdave** [comment]
I think people need to ask themselves "why do I make functions private?"

The answer in my opinion is to communicate that these functions are not
part of any external API. By making them private, you gain the ability to
change them without breaking anything.

That has absolutely nothing to do with testing :)

**Comment by RobertDober** [comment]
Well IIUC the idea is (and there is some value in it IMHO, but not enough to forbid it) that refactoring will break the tests of private functions and testing them is therefore brittle.
I am fine with that because tests at that level are spec of microbehavior and refactoring needs respecing, and I guess you agree with that. Anyway let us evolve and find the best mix (pun intended) for each project depending on that many factors like time size, project age, you name it...

Thank you for being such a great advocate for this beautiful language.
